# Generated by Django 5.2.1 on 2025-05-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactadmin',
            table='website_Contact',
        ),
    ]
