# Generated by Django 5.2.1 on 2025-05-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_contactadmin_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactAdmin',
            new_name='Contact',
        ),
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
    ]
