# Generated by Django 5.2.1 on 2025-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_contactadmin_contact_alter_contact_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-create_date']},
        ),
    ]
